name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-pages:
    name: deploy/pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v5
        with: { persist-credentials: false }

      - name: Use Node.js from nvmrc
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist

  # publish docker to GitHub registry
  deploy-docker:
    name: deploy/docker
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v5
      - run: docker build -t ghcr.io/maplibre/maputnik:main .
      - run: docker push ghcr.io/maplibre/maputnik:main
